

386_OBJECTS=\
 $(OBJ_PATH)\$O\swapbuffers.obj \


_RES_FILE=$(OBJ_PATH)\$O\swapbuffers.res



# lowercased
BASEDIR=c:\winddk\7600.16385.1
OBJECT_ROOT=c:\winddk\7600.16385.1
MAKEDIR_LOWERCASE=c:\users\danny\desktop\work\svn_programming\win32work\byteguard\drivertest\swapbuffers
OBJ_PATH=c:\users\danny\desktop\work\svn_programming\win32work\byteguard\drivertest\swapbuffers
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
